### ISSUE TITLE
Failed to activate the ruby-quick-test package

### ISSUE THREAD

**Issue by kangyunjk** [philnash/ruby-quick-test#18]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.207.0
**System**: Unknown Windows Version
**Thrown From**: [ruby-quick-test](https://github.com/philnash/ruby-quick-test) package, v0.3.0

### Stack Trace

Failed to activate the ruby-quick-test package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (C:\Users\BigMax\.atom\packages\ruby-quick-test\lib\ruby-quick-test-view.coffee:1:1)
  at C:\Users\BigMax\.atom\packages\ruby-quick-test\lib\ruby-quick-test-view.coffee:6:3
  at Object.<anonymous> (C:\Users\BigMax\.atom\packages\ruby-quick-test\lib\ruby-quick-test-view.coffee:133:5)
  at Object.<anonymous> (C:\Users\BigMax\.atom\packages\ruby-quick-test\lib\ruby-quick-test-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\BigMax\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\BigMax\.atom\packages\ruby-quick-test\lib\ruby-quick-test.coffee:1:21)
  at Object.<anonymous> (C:\Users\BigMax\.atom\packages\ruby-quick-test\lib\ruby-quick-test.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\BigMax\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\BigMax\AppData\Local\atom\app-0.207.0\resources\app.asar\src\package.js:707:34)
  at Package.module.exports.Package.activateConfig (C:\Users\BigMax\AppData\Local\atom\app-0.207.0\resources\app.asar\src\package.js:255:12)
  at Package.module.exports.Package.activateNow (C:\Users\BigMax\AppData\Local\atom\app-0.207.0\resources\app.asar\src\package.js:234:14)
  at C:\Users\BigMax\AppData\Local\atom\app-0.207.0\resources\app.asar\src\package.js:770:25
  at Emitter.module.exports.Emitter.emit (C:\Users\BigMax\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\BigMax\AppData\Local\atom\app-0.207.0\resources\app.asar\src\command-registry.js:219:20)
  at CommandRegistry.handleCommandEvent (C:\Users\BigMax\AppData\Local\atom\app-0.207.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\BigMax\AppData\Local\atom\app-0.207.0\resources\app.asar\src\command-registry.js:153:19)
  at EventEmitter.<anonymous> (C:\Users\BigMax\AppData\Local\atom\app-0.207.0\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -8:08.2.0 core:cut (atom-text-editor.editor.is-focused)
     -7:50 ruby-test:test-single (atom-text-editor.editor.is-focused)
     -6:27 core:confirm (atom-text-editor#ruby-test.shell.editor.mini.is-focused)
     -6:22.1.0 core:save (div.settings-view.pane-item)
  2x -6:13.2.0 ruby-test:test-file (ul.list-inline.tab-bar.inset-panel)
  9x -5:04.1.0 core:backspace (atom-text-editor#ruby-test.shell.editor.mini.is-focused)
     -4:52.5.0 ruby-test:test-file (ul.list-inline.tab-bar.inset-panel)
  2x -3:51.9.0 core:backspace (atom-text-editor#ruby-test.shell.editor.mini.is-focused)
     -3:44.8.0 ruby-test:test-single (ul.list-inline.tab-bar.inset-panel)
     -3:30.5.0 core:select-all (atom-text-editor.editor.is-focused)
     -3:25.9.0 ruby-test:test-file (atom-text-editor.editor.is-focused)
     -2:28.3.0 ruby-test:toggle (ul.list-inline.tab-bar.inset-panel)
     -2:16.4.0 core:backspace (atom-text-editor#ruby-test.testFileCommand.editor.mini.is-focused)
     -1:50.5.0 ruby-test:test-file (ul.list-inline.tab-bar.inset-panel)
     -1:41.9.0 core:cut (atom-text-editor#ruby-test.testFileCommand.editor.mini.is-focused)
     -0:15.5.0 ruby-quick-test:run-tests (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Atom-Localization, v1.16.1
autocomplete-ruby, v0.1.0
ruby-quick-test, v0.3.0
ruby-test, v0.9.11

# Dev
No dev packages
```

**Comment by jbosse** [comment]
[Enter steps to reproduce below:]

1. Open test file
2. type Ctrl + Cmd + T

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [ruby-quick-test](https://github.com/philnash/ruby-quick-test) package, v0.3.0


### Stack Trace

Failed to activate the ruby-quick-test package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/jamesbosse/.atom/packages/ruby-quick-test/lib/ruby-quick-test-view.coffee:5:199)
    at /Users/jamesbosse/.atom/packages/ruby-quick-test/lib/ruby-quick-test-view.coffee:12:5
    at Object.<anonymous> (/Users/jamesbosse/.atom/packages/ruby-quick-test/lib/ruby-quick-test-view.coffee:133:5)
    at Object.<anonymous> (/Users/jamesbosse/.atom/packages/ruby-quick-test/lib/ruby-quick-test-view.coffee:135:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
     -0:00.4.0 ruby-quick-test:run-tests (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ruby-quick-test, v0.3.0
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by philnash** [comment]
This was due to deprecations that were removed. Ruby Quick Test 0.4.0 should now work again. Thanks for reporting!
