### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by gllmotell** [philnash/ruby-quick-test#20]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 ia32
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [ruby-quick-test](https://github.com/philnash/ruby-quick-test) package 0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At C:\Users\Main\.atom\packages\ruby-quick-test\lib\ruby-quick-test-view.coffee:65

TypeError: Cannot read property 'path' of null
    at RubyQuickTestView.module.exports.RubyQuickTestView.activeFile (/packages/ruby-quick-test/lib/ruby-quick-test-view.coffee:65:77)
    at RubyQuickTestView.module.exports.RubyQuickTestView.testFileType (/packages/ruby-quick-test/lib/ruby-quick-test-view.coffee:68:19)
    at RubyQuickTestView.module.exports.RubyQuickTestView.runTests (/packages/ruby-quick-test/lib/ruby-quick-test-view.coffee:51:13)
    at /packages/ruby-quick-test/lib/ruby-quick-test-view.coffee:1:1)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:350265)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:348740)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:1:767067)
    at EventEmitter.t (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:1:774990)
    at EventEmitter.emit (events.js:200:13)
    at Object.onMessage (~/AppData/Local/atom/app-1.53.0/resources/electron.asar/renderer/init.js:42:16)
```

### Commands

```
     -4:42.9.0 levels:start-execution (atom-workspace.workspace.scrollbars-visible-always.theme-rainbow-syntax.theme-one-dark-ui)
  2x -4:07.7.0 editor:newline (input.hidden-input)
  3x -3:54.5.0 core:backspace (input.hidden-input)
     -3:38.4.0 settings-view:open (input.hidden-input)
  2x -2:57.2.0 editor:newline (input.hidden-input)
     -2:52.4.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -2:24.7.0 editor:newline (input.hidden-input)
     -0:59.2.0 core:paste (span.syntax--entity.syntax--name.syntax--function)
     -0:25.1.0 ruby-quick-test:run-tests (input.hidden-input)
```

### Non-Core Packages

```
aligner-ruby 1.7.0 
atom-runner 2.7.1 
autocomplete-ruby 0.2.8 
blueforest-syntax 0.5.1 
chubrub 0.2.0 
chuby-ninja 0.1.0 
fruits-syntax 0.0.7 
glitterbomb 0.2.0 
ide-ruby 0.5.0 
levels 0.6.1 
levels-debugger-ruby 0.5.9 
levels-language-ruby 0.5.9 
linter-spell-ruby 0.4.0 
operator-mono 0.11.0 
rainbow-syntax 2.4.0 
ruby-block 0.3.6 
ruby-block-converter 4.1.1 
ruby-blue-syntax 0.2.2 
ruby-dust-syntax 0.9.0 
ruby-quick-test 0.4.0 
ruby-robot-theme 1.0.0 
ruby-snippets 0.2.1 
ruby-solargraph 0.6.1 
ruby-syntax-replacer 0.5.1 
ruby-test-switcher 1.2.3 
sbrubbles-dark-syntax 0.7.0 
textmate-ruby-blue-syntax 0.2.0 
textmate-rubyrobot-syntax 0.1.0 
vibrant-ink-ruby 2.2.0 
xeta-syntax 0.5.0 
```

**Comment by philnash** [comment]
Hey, thanks for raising this issue. I haven't done anything with this plugin for a long time and I don't use Atom myself.

If you wanted to look into what has gone wrong (apparently [`atom.workspace.getActiveTextEditor().buffer.file` is `null`](https://github.com/philnash/ruby-quick-test/blob/master/lib/ruby-quick-test-view.coffee#L65)) and send a PR, I'd be happy to merge it.
